name: Composite Caller

on:
    workflow_dispatch:

jobs:
    call-composite-action:
        runs-on: ubuntu-latest
        steps:
            
            - name: 'Checkout repo'
              uses: actions/checkout@v5

            - name: Call composite output action
              id: composite-calling-step
              uses: ./.github/actions/composite-output-action
              with:
                message: "hello from composite-caller.yml"
            
            - name: Show composite action output
              run: echo 'Composite action output --> ${{ steps.composite-calling-step.outputs.composite-action-output }}'
