# This workflow shows how an output can be set in one job, then referenced in another job within the SAME workflow. 
# Jobs that reference the output of another job must use the 'needs' keyword to specify they are dependent on the job that set the output
on:

    workflow_dispatch:

jobs:
    job-that-sets-output:
        runs-on: ubuntu-latest
        outputs:
            job-output: ${{ steps.set-output-step.outputs.step-output }}
        steps:
            - name: Set output 
              id: set-output-step
              run: echo 'step-output=This output was set in "job-that-sets-output"!' >> $GITHUB_OUTPUT
    
    job-that-uses-output:
        needs: job-that-sets-output
        runs-on: ubuntu-latest
        steps:
            - name: Echo output from 'job-that-sets-output'
              run: echo 'The output from job-that-sets-output is "${{ needs.job-that-sets-output.outputs.job-output }}"'