on:

    workflow_dispatch:

    # This is only here to get the workflow to show up in the UI initially. It should be removed when the workflow is ready to be used.
    push:

jobs:
    outputs-between-same-job:
        runs-on: ubuntu-latest
        env:
            YELLOW: '\033[33m'
            END_COLOR: '\033[0m'
        steps:
            - name: Set single-line output
              id: set-output
              run: echo 'single-line-output=This single-line output is set and referenced in the same workflow job!' >> $GITHUB_OUTPUT
            
            - name: Echo single-line output that was set in the same job
              env: 
                hey: ${{ steps.set-output.outputs.single-line-output }}
              run: printf 'Output from the same job is ${YELLOW}${{env.hey}}${END_COLOR}'
            
            - name: Set multi-line output
              id: set-multi-line-output
              run: |
                echo "multi-line-output<<EOF" >> $GITHUB_OUTPUT
                echo "This is the first line of a multi-line output." >> $GITHUB_OUTPUT
                echo "This is the second line of a multi-line output." >> $GITHUB_OUTPUT
                echo "EOF" >> $GITHUB_OUTPUT

            - name: Echo multi-line output that was set in the same job
              run: echo -e 'Multi-line Output from the same job is ${YELLOW}${{ steps.set-multi-line-output.outputs.multi-line-output }}${END_COLOR}'