on:

    workflow_dispatch:

    # This is only here to get the workflow to show up in the UI initially. It should be removed when the workflow is ready to be used.
    push:

jobs:
    outputs-between-same-job:
        runs-on: ubuntu-latest
        env:
            YELLOW: '\033[33m'
            YELLOW2: $'\033[33m'
            END_COLOR: '\033[0m'
            END_COLOR2: $'\033[0m'
        steps:
            - name: Set single-line output
              id: set-output
              run: echo 'single-line-output=This single-line output is set and referenced in the same workflow job!' >> $GITHUB_OUTPUT
            
            - name: Use env var to reference single-line output that was set in the same job
              # You don't need to set an output as an environment variable to reference it in the same job, this just demonstrates that it can be done.
              env: 
                above-output: ${{ steps.set-output.outputs.single-line-output }}
              # printf is another way to output statements. The %s is a placeholder for a string, which is essentially an argument. 
              # The second string must be in its own set of quotes to be properly read as an argument. 
              run: |
                printf "env.above-output was set to the output of the above step!"
                printf "Output from the same job is ${YELLOW}%s${END_COLOR}\n" "${{env.above-output}}"
            
            - name: Set multi-line output
              id: set-multi-line-output
              run: |
                echo "multi-line-output<<EOF" >> $GITHUB_OUTPUT
                echo "This is the first line of a multi-line output." >> $GITHUB_OUTPUT
                echo "This is the second line of a multi-line output." >> $GITHUB_OUTPUT
                echo "EOF" >> $GITHUB_OUTPUT

            - name: Printf multi-line output that was set in the same job
              run: |
                printf "Multi-line output from the same job is: \n" 
                # Take the multi-line output and use a pipe to use it as input for the while loop
                # We do printf "%s" "<output>" instead of just printf "<output>" to preserve all characters the multi-line output literally. The other way risks things like %, \, and - being interpreted incorrectly.
                # The while loop is needed to preserve the multi-line formatting when printing the output.
                # IFS is set to null to preserve leading/trailing whitespace and to prevent collapsing of consecutive whitespace.
                # read splits the input via \n, it always considers \n as a delimiter. The -r flag prevents lets backslashes be treated as literals (not as escape characters). 
                # Each delimited string is known as 'line'
                printf "%s\n" "${{ steps.set-multi-line-output.outputs.multi-line-output }}" | while IFS= read -r line; do
                  printf "${YELLOW2}%s${END_COLOR2}\n" "$line"
                done