# This is the innermost workflow when it comes to workflow-a, workflow-b, and workflow-c. It is called by workflow-b, which is in turn called by workflow-a. 
# The output of this workflow is passed to workflow-b, which then passes it to workflow-a.

on:
  workflow_call:
    outputs:
      workflow-c-output:
        description: "Workflow-C output"
        value: ${{ jobs.set-workflow-c-output-job.outputs.workflow-c-output }}

jobs:
  set-workflow-c-output-job:
    runs-on: ubuntu-latest
    outputs:
      # This references the step with the id of "set-hello". 
      workflow-c-output: ${{ steps.set-workflow-c-output-step.outputs.workflow-c-output }}
    steps:

      # Need to checkout repo for reusable workflows to reference one another. 
      # In the workflow-a/b/c cadence, only workflow-c checks out the repo because it is the innermost workflow
      # Since workflow-b references workflow-c, and workflow-a references workflow-b, workflow-a and workflow-b thus do not need to checkout the repo.
      # workflow-c still functions within the context of workflow-a because workflow-a is the original workflow that started this cadence.
      # workflow-a and workflow-b could also checkout the repo in other non-calling jobs, but actions/checkout would still have to be run in workflow-c because jobs execute on different runners.  
      - name: 'Checkout repo'
        uses: actions/checkout@v4

      # This step sets the output, thus the need for an id.
      - name: "Set workflow-c-output"
        id: set-workflow-c-output-step
        run: |
          echo "workflow-c-output=HELLO from workflow-c!" >> $GITHUB_OUTPUT