# This is the innermost workflow when it comes to workflow-a, workflow-b, and workflow-c. It is called by workflow-b, which is in turn called by workflow-a. 
# The output of this workflow is passed to workflow-b, which then passes it to workflow-a.

on:
  workflow_call:
    outputs:
      workflow-c-output:
        description: "Workflow-C output"
        value: ${{ jobs.set-workflow-c-output.outputs.workflow-c-output }}

jobs:
  set-workflow-c-output:
    runs-on: ubuntu-latest
    outputs:
      # This references the step with the id of "set-hello". 
      workflow-c-output: ${{ steps.set-hello.outputs.workflow-c-output }}
    steps:
      # This step sets the output, thus the need for an id.
      - name: "Set workflow-c-output"
        id: set-hello
        run: |
          echo "workflow-c-output=HELLO from workflow-c!" >> $GITHUB_OUTPUT