
# This is the 'middle' workflow. It is called by workflow-a, and calls workflow-c.
on:
  workflow_call:
    outputs:
      workflow-b-output:
        description: "Workflow-B output"
        value: ${{ jobs.get-workflow-c-output.outputs.workflow-c-output }}

jobs:
  get-workflow-c-output:
    # TODO UPDATE WITH REF (SHA, TAG, ETC)
    uses: ./.github/workflows/workflow-c.yml
    