# TODO DESCRIBE! OUTERMOST

on:

    workflow_dispatch:

jobs:
    call-workflow-b:
        uses: ./.github/workflows/workflow-b.yml

    echo-output-from-b:
        needs: call-workflow-b
        runs-on: ubuntu-latest
        steps:
            - name: Echo output from workflow-b
              run: echo "Output from workflow-b: ${{ needs.call-workflow-b.outputs.workflow-b-output }}"