# This is the OUTERMOST workflow. It calls workflow-b, which in turn calls workflow-c.

on:

    workflow_dispatch:

jobs:
    call-workflow-b:
        uses: ./.github/workflows/workflow-b.yml

    echo-output-from-b:
        needs: call-workflow-b
        runs-on: ubuntu-latest
        steps:
            - name: Echo output from workflow-b
              run: echo 'workflow-a says Output from workflow-b is "${{ needs.call-workflow-b.outputs.workflow-b-output }}"'